#CI项目名
name: Redmi-AX6-immortalwrt-5.15

on:
  #对应的是 UTC 时间，需要转换，0 代表北京时间8点，每个月5日/19日16点编译一次
  #关闭则手动编译
  workflow_dispatch:
  schedule:
    - cron: 0 8 5,19 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  owrt_config:
    #调用公用编译核心OWRT-CORE.yml
    uses: ./.github/workflows/OWRT-CORE-MO.yml
    with:
      #编译平台，X64包含X86
      OWRT_TARGET: Redmi-AX6-immortalwrt
      #默认主题
      OWRT_THEME: argon
      #默认主机名
      OWRT_NAME: Redmi-AX6
      #默认密码，仅作展示，更改无效
      OWRT_PW: password
      #默认地址
      OWRT_IP: 192.168.31.1
      #默认源码
      OWRT_URL: https://github.com/immortalwrt/immortalwrt
      #源码版本
      OWRT_BRANCH: openwrt-23.05
      #自定义config
      OWRT_CFG: diy_imoutowrt-5.15.config     
      #设备类型
      OWRT_TYPE: 红米AX6
      OWRT_LINUX: 5.15.x
      OWRT_FILES: ax6/files
